version: "3"
services:
  app:
    build:
      context: ./docker
    container_name: focalboard
    expose: 
      - 8000
    environment:
      - VIRTUAL_HOST=focalboard.local
      - VIRTUAL_PORT=8000
  
  proxy:
    image: jwilder/nginx-proxy:latest
    container_name: focalboard-proxy
    ports:
      - 443:443
    volumes:
      - "./certs:/etc/nginx/certs:ro"
      - "/var/run/docker.sock:/tmp/docker.sock:ro"

  postgres:
    image: postgres:latest
    container_name: focalboard-postgres
    restart: always
    volumes:
      - "./data:/var/lib/postgresql/data"
    environment:
      POSTGRES_DB: boards
      POSTGRES_USER: boarduser
      POSTGRES_PASSWORD: board-password

