version: "3"
services:
  app:
    build:
      context: ./
    container_name: focalboard
    ports: 
      - 80:8000
    environment:
      - VIRTUAL_HOST=focalboard.local
      - VIRTUAL_PORT=8000

