version: '2.4'
services:
  mariadb:
    image: "mariadb:10.9.3"
    restart: always
    environment:
      MARIADB_ROOT_HOST: "%"
      MARIADB_ROOT_PASSWORD: mostest
      MARIADB_PASSWORD: mostest
      MARIADB_USER: mmuser
    healthcheck:
      test: ["CMD", "mariadb-admin", "ping", "-h", "localhost", "-u", "mmuser", "-pmostest"]
      interval: 5s
      timeout: 10s
      retries: 3
    tmpfs: /var/lib/mariadb
    ports:
      - 44445:3306

  start_dependencies:
    image: mattermost/mattermost-wait-for-dep:latest
    depends_on:
      - mariadb
    command: mariadb:3306
