name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  ubuntu:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: npm install
      run: cd webapp; npm install

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15

    - name: Build server Linux package
      run: make server-linux-package

    - name: Copy server binary for Cypress
      run: cp bin/linux/octoserver bin/

    - name: Upload server package
      uses: actions/upload-artifact@v1
      with:
        name: octo-linux-amd64.tar.gz
        path: ${{ github.workspace }}/dist/octo-linux-amd64.tar.gz

    - name: ESLint
      run: cd webapp; npm run check

    - name: "Test webapp: Jest"
      run: cd webapp; npm run test

    - name: "Test webapp: Cypress"
      run: "cd webapp; npm run cypress:ci"

    - name: Test server
      run: make server-test

  macos:
    runs-on: macos-10.15

    steps:

    - name: Checkout
      uses: actions/checkout@v2

    - name: npm install
      run: cd webapp; npm install

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15

    - name: List Xcode versions
      run: ls -n /Applications/ | grep Xcode*

    - name: Build macOS
      run: make mac-app
      env:
        DEVELOPER_DIR: /Applications/Xcode_12.3.app/Contents/Developer

    - name: Upload macOS package
      uses: actions/upload-artifact@v1
      with:
        name: tasks-mac.zip
        path: ${{ github.workspace }}/mac/dist/tasks-mac.zip

