name: Build-Mac

on: workflow_dispatch

jobs:

  macos:
    runs-on: macos-10.15

    steps:

    - name: Checkout
      uses: actions/checkout@v2

    - name: Replace token 1
      uses: jacobtomlinson/gha-find-replace@master
      with:
        find: "placeholder_rudder_dataplane_url"
        replace: "${{ secrets.RUDDER_DATAPLANE_URL }}"
        include: server/services/telemetry/telemetry.go

    - name: Replace token 2
      uses: jacobtomlinson/gha-find-replace@master
      with:
        find: "placeholder_rudder_key"
        replace: "${{ secrets.RUDDER_DEV_KEY }}"
        include: server/services/telemetry/telemetry.go

    - name: npm install
      run: cd webapp; npm install --no-optional

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15

    - name: List Xcode versions
      run: ls -n /Applications/ | grep Xcode*

    - name: Build macOS
      run: make mac-app
      env:
        DEVELOPER_DIR: /Applications/Xcode_12.3.app/Contents/Developer

    - name: Upload macOS package
      uses: actions/upload-artifact@v1
      with:
        name: tasks-mac.zip
        path: ${{ github.workspace }}/mac/dist/tasks-mac.zip

