name: Build-Ubuntu

on: workflow_dispatch

jobs:

  ubuntu:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: npm install
      run: cd webapp; npm install --no-optional

    - name: Replace tokens 1
      run: perl -pi -e 's/placeholder_rudder_dataplane_url/"$ENV{RUDDER_DATAPLANE_URL}"/' ${{ github.workspace }}/server/services/telemetry/telemetry.go
      env:
        RUDDER_DATAPLANE_URL: ${{ secrets.RUDDER_DATAPLANE_URL }}

    - name: Replace tokens 2
      run: perl -pi -e 's/placeholder_rudder_key/"$ENV{RUDDER_KEY}"/' ${{ github.workspace }}/server/services/telemetry/telemetry.go
      env:
        RUDDER_KEY: ${{ secrets.RUDDER_DEV_KEY }}

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15

    - name: apt-get libgtk-3-dev
      run: sudo apt-get install libgtk-3-dev

    - name: apt-get libwebkit2gtk-4.0-dev
      run: sudo apt-get install libwebkit2gtk-4.0-dev

    - name: Build Linux server and app
      run: make server-linux-package linux-app

    - name: Upload server package
      uses: actions/upload-artifact@v1
      with:
        name: octo-linux-amd64.tar.gz
        path: ${{ github.workspace }}/dist/octo-linux-amd64.tar.gz

    - name: Upload app package
      uses: actions/upload-artifact@v1
      with:
        name: tasks-linux.tar.gz
        path: ${{ github.workspace }}/linux/dist/tasks-linux.tar.gz
