name: golangci-lint

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  golangci:
    name: server
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/setup-go@v2
        with:
          go-version: 1.16
      - uses: actions/checkout@v2
      - name: server-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.41
          working-directory: server
          skip-go-installation: true
